'''
{'id': 'lBPqgBowX1CsjHay12LY', 'companyId': 'lp2p1q27DrdGta1qGDJd', 'name': 'Nestle LLC - SOMA TEST', 'address': '4th fleet street', 'city': 'New York', 'state': 'Illinois', 'country': 'US', 'postalCode': '567654', 'website': 'https://yourwebsite.com', 'timezone': 'US/Central', 'firstName': 'John', 'lastName': 'Doe', 'email': 'john.doe@mail.com', 'phone': '+1410039940', 'business': {'name': 'Nestle LLC - SOMA TEST', 'address': '4th fleet street', 'city': 'New York', 'state': 'Illinois', 'country': 'US', 'postalCode': '567654', 'website': 'https://yourwebsite.com', 'timezone': 'US/Central'}, 'social': {'facebookUrl': 'https://www.facebook.com/', 'googlePlus': 'https://www.googleplus.com/', 'linkedIn': 'https://www.linkedIn.com/', 'foursquare': 'https://www.foursquare.com/', 'twitter': 'https://www.foutwitterrsquare.com/', 'yelp': 'https://www.yelp.com/', 'instagram': 'https://www.instagram.com/', 'youtube': 'https://www.youtube.com/', 'pinterest': 'https://www.pinterest.com/', 'blogRss': 'https://www.blogRss.com/', 'googlePlacesId': 'ChIJJGPdVbQTrjsRGUkefteUeFk'}, 'settings': {'allowDuplicateContact': False, 'allowDuplicateOpportunity': False, 'allowFacebookNameMerge': False, 'disableContactTimezone': False, 'contactUniqueIdentifiers': ['email', 'phone']}, 'dateAdded': '2024-11-17T01:02:55.684Z', 'domain': '', 'traceId': 'd307468a-b20f-456e-8bd4-d611e7d883d3'}
'''

sub_account_id = 'lBPqgBowX1CsjHay12LY'
companyId =  'lp2p1q27DrdGta1qGDJd'
Agency_Access_Key = 'pit-ad700aa3-8481-4cff-b555-bcaac7532592'
subaccount_Access_Key = 'xxxxxxxxxxxxxxxxxxxxx'
#https://labs.heygen.com/interactive-avatar/share?share=eyJxdWFsaXR5IjoiaGlnaCIsImF2YXRhck5hbWUiOiJmOGU0M2FlZTk2YmQ0MzgzYWZmNDY1Njkx%0D%0AZDU4NjgxZiIsInByZXZpZXdJbWciOiJodHRwczovL2ZpbGVzMi5oZXlnZW4uYWkvYXZhdGFyL3Yz%0D%0AL2Y4ZTQzYWVlOTZiZDQzODNhZmY0NjU2OTFkNTg2ODFmL2Z1bGwvMi4yL3ByZXZpZXdfdGFyZ2V0%0D%0ALndlYnAiLCJuZWVkUmVtb3ZlQmFja2dyb3VuZCI6ZmFsc2UsImtub3dsZWRnZUJhc2VJZCI6Ijdj%0D%0ANGRhNjM5MDkxNDQ2NDY5ZWFkM2Y2MGNhYWE0NmU4Iiwic2hhcmVfY29kZSI6IjM5ZTc0NjE3LTk2%0D%0AMTYtNDc2Yy1iZmM3LWZmNmE1ZjBiYjJjZCIsInVzZXJuYW1lIjoiNzQ5MTY5M2Q4YTJkNGZlMTgy%0D%0ANDlhNWY1NzcwMDBkMjAifQ%3D%3D

import requests

url = "https://services.leadconnectorhq.com/users/"

payload = {
    "companyId": companyId,
    "firstName": "GRAPE LLC",
    "lastName": "Soma -Test",
    "email": "dmacproject123@gmail.com",
    "password": "Grape@1357",
    "phone": "+17166044030",
    "type": "account",
    "role": "admin",
    "locationIds": [sub_account_id],
    "permissions": {
        "campaignsEnabled": True,
        "campaignsReadOnly": False,
        "contactsEnabled": True,
        "workflowsEnabled": True,
        "workflowsReadOnly": True,
        "triggersEnabled": True,
        "funnelsEnabled": True,
        "websitesEnabled": False,
        "opportunitiesEnabled": True,
        "dashboardStatsEnabled": True,
        "bulkRequestsEnabled": True,
        "appointmentsEnabled": True,
        "reviewsEnabled": True,
        "onlineListingsEnabled": True,
        "phoneCallEnabled": True,
        "conversationsEnabled": True,
        "assignedDataOnly": False,
        "adwordsReportingEnabled": False,
        "membershipEnabled": False,
        "facebookAdsReportingEnabled": False,
        "attributionsReportingEnabled": False,
        "settingsEnabled": True,
        "tagsEnabled": True,
        "leadValueEnabled": True,
        "marketingEnabled": True,
        "agentReportingEnabled": True,
        "botService": False,
        "socialPlanner": True,
        "bloggingEnabled": True,
        "invoiceEnabled": True,
        "affiliateManagerEnabled": True,
        "contentAiEnabled": True,
        "refundsEnabled": True,
        "recordPaymentEnabled": True,
        "cancelSubscriptionEnabled": True,
        "paymentsEnabled": True,
        "communitiesEnabled": True,
        "exportPaymentsEnabled": True
    },
    "scopes": [
    "campaigns.readonly",
    "campaigns.write",
    "calendars/events.write",
    "calendars/events.readonly",
    "contacts.write",
    "contacts/bulkActions.write",
    "workflows.readonly",
    "workflows.write",
    "triggers.write",
    "funnels.write",
    "websites.write",
    "opportunities.write",
    "opportunities/leadValue.readonly",
    "reporting/phone.readonly",
    "reporting/adwords.readonly",
    "reporting/facebookAds.readonly",
    "reporting/attributions.readonly",
    "reporting/agent.readonly",
    "payments.write",
    "payments/refunds.write",
    "payments/records.write",
    "payments/exports.write",
    "payments/subscriptionsCancel.write",
    "invoices.write",
    "invoices.readonly",
    "invoices/schedule.readonly",
    "invoices/schedule.write",
    "invoices/template.readonly",
    "invoices/template.write",
    "reputation/review.write",
    "reputation/listing.write",
    "conversations.write",
    "conversations.readonly",
    "conversations/message.readonly",
    "conversations/message.write",
    "contentAI.write",
    "dashboard/stats.readonly",
    "locations/tags.write",
    "locations/tags.readonly",
    "marketing.write",
    "eliza.write",
    "settings.write",
    "socialplanner/post.write",
    "marketing/affiliate.write",
    "blogs.write",
    "membership.write",
    "communities.write",
    "certificates.write",
    "certificates.readonly",
    "adPublishing.write",
    "adPublishing.readonly"
    ],
    "scopesAssignedToOnly": [
    "campaigns.readonly",
    "campaigns.write",
    "calendars/events.write",
    "calendars/events.readonly",
    "contacts.write",
    "contacts/bulkActions.write",
    "workflows.readonly",
    "workflows.write",
    "triggers.write",
    "funnels.write",
    "websites.write",
    "opportunities.write",
    "opportunities/leadValue.readonly",
    "reporting/phone.readonly",
    "reporting/adwords.readonly",
    "reporting/facebookAds.readonly",
    "reporting/attributions.readonly",
    "reporting/agent.readonly",
    "payments.write",
    "payments/refunds.write",
    "payments/records.write",
    "payments/exports.write",
    "payments/subscriptionsCancel.write",
    "invoices.write",
    "invoices.readonly",
    "invoices/schedule.readonly",
    "invoices/schedule.write",
    "invoices/template.readonly",
    "invoices/template.write",
    "reputation/review.write",
    "reputation/listing.write",
    "conversations.write",
    "conversations.readonly",
    "conversations/message.readonly",
    "conversations/message.write",
    "contentAI.write",
    "dashboard/stats.readonly",
    "locations/tags.write",
    "locations/tags.readonly",
    "marketing.write",
    "eliza.write",
    "settings.write",
    "socialplanner/post.write",
    "marketing/affiliate.write",
    "blogs.write",
    "membership.write",
    "communities.write",
    "certificates.write",
    "certificates.readonly",
    "adPublishing.write",
    "adPublishing.readonly"
    ]

}
headers = {
    "Authorization": f"Bearer {Agency_Access_Key}",
    "Version": "2021-07-28",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

response = requests.post(url, json=payload, headers=headers)

print(response.json())